- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
Enable the application to ping connections to ensure that they're alive.
Add method `ping` in `WalletConnection`. The `BrowserWallet` implementation is a noop, in `WalletConnect` it delegates to the ping method of the underlying client.
Resolves #7.
> Add ability to ping connections

- packages/react-components/src/WithWalletConnector.ts
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
The disconnect handler has been renamed for consistence.
It's intended future usage is to allow applications using react-components to connect directly using `WalletConnector.connect` instead of having to use the function exposed by the `WithWalletConnector` component. The component will then be notified of the connection and register it appropriately.
> wallet-connectors: Add event handler for newly established connection 

- packages/react-components/src/useContractSelector.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
- samples/contractupdate/package.json
- samples/contractupdate/src/App.tsx
- samples/contractupdate/src/ConnectedAccount.tsx
- samples/contractupdate/src/ContractInvoker.tsx
- samples/contractupdate/src/NetworkSelector.tsx
- samples/contractupdate/src/Root.tsx
- samples/contractupdate/src/useContractSchemaRpc.ts
- yarn.lock
Changes extracted from [the refactor PR](https://github.com/Concordium/concordium-dapp-libraries/pull/6) that weren't actually relevant to that PR:
- `ContractSelector`: Renamed `validationError` to `error` to reflect that it isn't necessarily validation error.
- Sample dapp: Removed direct dependency on `@concordium/wallet-connectors` as `react-components` re-exports the library (see https://github.com/Concordium/concordium-dapp-libraries/commit/f571d59feee65581ea1750b3126aec4389281a5a) and migrate imports.
> Minor cleanup

- README.md
- packages/react-components/CHANGELOG.md
- packages/react-components/README.md
- packages/react-components/package.json
- packages/react-components/src/WithWalletConnector.ts
- packages/react-components/src/useWalletConnectorSelector.ts
- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/README.md
- packages/wallet-connectors/src/WalletConnect.ts
- samples/contractupdate/src/Root.tsx
- samples/contractupdate/src/WalletConnectionButton.tsx
- samples/contractupdate/src/config.ts
- yarn.lock
Decouple component `WithWalletConnector` from concrete `WalletConnector` implementations by constructing instances from the application. This allows the component to accept custom connector implementations as it only refers to the shared interface. In particular, it means that the component no longer expects the misfitting `walletConnectOpts` prop. It also allows the application to control the lifecycle of the connectors.
Make `ConnectorType` an interface instead of a string enum. This interface controls the activation/deactivation lifecycle of the connectors, including construction of new connector instances. Two implementations of this interface are included, both of which are implemented as functions: One that only keeps connectors alive while they're active (`ephemeralConnectorType`; …
> react-components: Let application provide connector instances

- packages/react-components/src/WithWalletConnector.ts
- samples/contractupdate/src/ContractInvoker.tsx
Make it visible in the dApp that it's waiting for the use to approve an action in the wallet. And prevent the user from submitting again until the first action is approved or rejected.
Add waiting indicator state and use it to disable the submit button.
Resolves #14.
> contractupdate: Add indicator when waiting for approval

- packages/react-components/src/WithWalletConnector.ts
- packages/react-components/src/error.ts
- packages/react-components/src/useContractSelector.ts
- samples/contractupdate/src/ContractInvoker.tsx
- samples/contractupdate/src/Root.tsx
- samples/contractupdate/src/useContractSchemaRpc.ts
- samples/contractupdate/src/util.ts
- samples/contractupdate/tsconfig.json
Ensure that non-`Error` exceptions don't go undetected.
Compared to the usual strategy of using `(err as Error).message`, this function adds a fallback to just treating the value as a string. This avoids errors that aren't actually of type `Error` to be masked as described in https://concordium.atlassian.net/browse/CBW-780.
> Add utility function for extracting string from error

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
Ensure that `BrowserWallet.getConnections` only returns a connection if the user has asked for it to be "connected".
Add a field to `BrowserWallet` to indicate whether the connection is "established". Using the presence of an account like before is not enough as the account could be available on a fresh page load. But as the delegate's `onConnected` method isn't called until `connect` is called. This means that the account would be missing in any state maintained by the delegate.
This solution also allows the connection to be marked as disconnected later on.
As no implementations of `getConnections` are really asynchronous anymore, we also change the interface method to non-async. This makes sense as connectors really should be able to know about their connections directly.
> wallet-connectors: Improve 'getConnections'

- packages/react-components/src/WithWalletConnector.ts
- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
The account is usually (as in all current instances) known at the time that the connection has been established. Instead of the application having to poll it (asynchronously) from the connection, we might as well pass it up front.
> wallet-connectors: Add account to 'onConnected'

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/package.json
This is a patch release that includes a small fix. It also serves as a test to https://github.com/Concordium/concordium-dapp-libraries/pull/23.
> wallet-connectors: Bump version for release

- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- yarn.lock
The version was pinned as it didn't have a `^`. The version is now unpinned to allow patch upgrades.
> react-components: Bump wallet-connectors dependency

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/src/WalletConnect.ts
It's unclear why this was done this way but it's definitely wrong.
> wallet-connectors: Don't stringify 'signMessage' result

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/package.json
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
- packages/wallet-connectors/src/error.ts
- samples/contractupdate/package.json
- samples/contractupdate/src/ContractInvoker.tsx
- samples/contractupdate/src/useContractSchemaRpc.ts
- yarn.lock
Allow smart contract invocation parameters provided to `WalletConnection.signAndSendTransaction(...)` to be encoded using parameter schemas rather than only full module schemas.
This also fixes the current inability to invoke contract methods that don't take parameters.
Replace the `parameters` and `schemaVersion` parameters of `signAndSendTransaction` with a new union type `Schema`.
The interface requirements for the method was also tightened up and made consistent between both implementations.
This PR is an alternative to #33.
> wallet-connectors: Support encoding parameters using all schema types

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
- samples/contractupdate/src/ContractInvoker.tsx
- samples/sign-message/src/App.tsx
- samples/sign-message/src/util.ts
Add support for signing both string and binary messages in the `WalletConnection` interface. Fully implemented for Browser Wallet, partially for WalletConnect.
Replaced the `string` message type in `signMessage` with a new type `SignableMessage` which is a discriminated union of a binary message (which has a *type/parameter* schema) and a simple string message.
The mobile wallets don't yet support signing binary messages, so the WalletConnect implementation throws an exception for that case. It's very non-desirable to throw exceptions at use time for unimplemented features as compared to enabling the dApp to detect available features for a given connection. But in this case, the warts that this would impose on the interface are not deemed worth it: The MW aren't lacking the feature, it's …
> wallet-connectors: Add support for signing both string and binary messages

- .github/workflows/build+release.yml
- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/package.json
- yarn.lock
Fix CI workflow for releasing package.
Workflow:
- Build NPM package pack-file using `npm pack` instead of zipping manually and upload that.
- Prepare for releasing that file using `npm publish` (is currently dry-run as the repo doesn't have the credentials). This will be added later, either in this workflow or a separate one that triggers on a release being created (or manually).
- Use new action `bisgardo/github-action-echo` to define variables in a way that's much nicer than explicitly `echo`ing to a file.
Additionally, the `wallet-conections` version was bumped and will be released when this is merged.
> wallet-connections: Bump version and fix release workflow

- packages/react-components/CHANGELOG.md
- packages/react-components/README.md
- packages/react-components/package.json
- packages/react-components/src/index.ts
- packages/react-components/src/useContractSelector.ts
- packages/react-components/src/useGrpcClient.ts
- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/README.md
- packages/wallet-connectors/package.json
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
- packages/wallet-connectors/src/index.ts
- samples/contractupdate/src/App.tsx
- samples/contractupdate/src/ConnectedAccount.tsx
- samples/contractupdate/src/Root.tsx
- samples/contractupdate/src/config.ts
- samples/sign-message/src/App.tsx
- samples/sign-message/src/config.ts
- yarn.lock
Add support for using the gRPC client for API version 2 and match BW deprecation of JSON-RPC.
Deprecated the existing method `getJsonRpcClient` on `WalletConnection` in `wallet-connectors` in favor of the new hook `useGrpcClient` in `react-components`.
Standard network configurations have been added to `wallet-connectors` for testnet and mainnet as constants that were extracted from the sample dApps. A field holding gRPC Web client options was added to `Network` with standard URLs `https://grpc.testnet.concordium.com` and `https://grpc.mainnet.concordium.software` for testnet and mainnet, respectively.
Resolves [CBW-947](https://concordium.atlassian.net/browse/CBW-947).
[CBW-947]: https://concordium.atlassian.net/browse/CBW-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
> Deprecate JSON-RPC support and add support for using the gRPC client for Node API v2

- samples/contractupdate/src/App.tsx
- samples/contractupdate/src/ContractInvoker.tsx
- samples/contractupdate/src/useContractSchemaRpc.ts
The JSON-RPC client is deprecated and replaced with the gRPC client. When merging that change, only one of the RPC usages in the sample dApp were migrated. This migrates the other use (to use the same client). As the new client is connection-independent, the query screen now appears immediately after the application has loaded.
A significant change is that the 'getModuleSource' method of gRPC client returns the module source without the module version and length (and actually another byte before that) prefix.
> contractupdate: Use gRPC client

- .github/workflows/build+release.yml
- .github/workflows/build+test.yml
- package.json
Avoid bad/incomplete changes to get merged into main or detected when they are.
Add CI workflow for checking formatting and running build and tests in all workspaces. The workflow is automatically triggered on updates to PRs or merges/direct pushes to `main`.
The project doesn't actually contain any tests atm., but once added, this ensures that they get checked.
> CI: Add workflow for testing libs and document release workflow

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/src/WalletConnect.ts
Ensure that schema objects are sent in the format expected by the Mobile Wallets.
Translate the `Schema` object into one that JSON encodes as expected by the Mobile Wallet Crypto library.
Currently the schema objects are sent directly which means that the `type` field has unexpected values and the value is converted to a `Buffer` (format `{type: "Buffer", data: [<bytes>]}`) instead of a base64 encoded string.
The Android wallet accepts the current payload but silently fails to decode the parameters and just prints "No parameters". I've verified that it prints the correct payload after this change. The iOS wallet's WalletConnect implementation is going to accept both formats.
> wallet-connectors: Fix schema object serialization for WalletConnect

- packages/wallet-connectors/src/WalletConnect.ts
- samples/contractupdate/src/useContractSchemaRpc.ts
Make fetching/parsing of contract schema more precise based on the module version information that is now exposed by the gRPC client.
This in turn also documents the relationship between module and schema versions.
Use module version to determine what custom sections to look for and add comments explaining the expected results.
> useContractSchemaRpc: Parse schema based on module version

- packages/react-components/CHANGELOG.md
- packages/react-components/README.md
- packages/react-components/src/useContractSelector.ts
- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/src/BrowserWallet.ts
- packages/wallet-connectors/src/WalletConnect.ts
- packages/wallet-connectors/src/WalletConnection.ts
- packages/wallet-connectors/src/index.ts
Remove support for the depreated JSON-RPC client as per [this strategy](https://concordium.atlassian.net/wiki/spaces/EN/pages/1185349645/Remove+V1+GRPC+API).
Remove all symbols related to `WalletConnection.getJsonRpcClient`.
> wallet-connectors: Remove deprecated JSON-RPC client integration

- packages/wallet-connectors/CHANGELOG.md
The latest commit erroneously added an item under a section for an existing release. This change moves it to the "unreleased" section where it belongs.
> wallet-connectors: Fix changelog

- .github/workflows/build+release.yml
- README.md
Make the `build+release` workflow actually publish the built packages to npmjs, not just as a dry-run.
Based on https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry.
The API key has been added as a repository secret.
> CI: Let release script publish to NPM registry

- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/jest.config.ts
- packages/wallet-connectors/package.json
- packages/wallet-connectors/src/WalletConnection.ts
- packages/wallet-connectors/test/WalletConnection.test.ts
- packages/wallet-connectors/tsconfig.test.json
- yarn.lock
Allow schema to not have base64 padding.
- Allow for no base64 padding in a schema.
hard-to-understand areas.
> Do not require padding on schema

- packages/react-components/package.json
- packages/wallet-connectors/CHANGELOG.md
- packages/wallet-connectors/package.json
- packages/wallet-connectors/src/WalletConnect.ts
- samples/contractupdate/src/config.ts
- samples/proofs/src/config.ts
- samples/sign-message/src/config.ts
- yarn.lock
Deep linking does not work with the deprecated `@walletconnect/qrcode-modal`. This PR aims to update the dependency. Additionally, I've added a method on the wallet connect connector for defining the scope of the connection made to a wallet (`connectWithScope`), as it seems there is not feature parity with regards to the supported wallet connect methods.
This is already used in the published alpha version in the gc voting application (added in https://github.com/Concordium/concordium-governance-committee-voting/pull/115).
hard-to-understand areas.
> Update wc modal

- packages/react-components/README.md
This reflects the change in #65 (3f6885acad09dce93db50667fd125026c90d879c) where the `WalletConnectNamespaceConfig` parameter was added.
> react-components: Update docs on configuring connector type
